In [ ]:
# numpy practice
import numpy as np
a=np.array([10,20,30])  # array initialization with numpy gives without comma
print(a)

[10 20 30]


In [ ]:
b=[10,20,30,40]  #list gives with comma
print(b)

[10, 20, 30, 40]


In [ ]:
print(a.shape)  #rows,columns
print(a.dtype)

(3,)
int64


In [8]:
np.ones((2,4))
np.zeros((3,3))
np.eye(4) #create a identity matrix of 4 dimensional

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
#indexing and slicing
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])
print(arr[1:4])

10
50
[20 30 40]


In [ ]:
#2D indexing
m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)
print(m[1,1])
print(m[:,1]) #cant understand yet

[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[2 5 8]


In [14]:
a=25
ba=4
a+ba*ba/ba**2*np.sqrt(a)

np.float64(30.0)

In [ ]:
a=2
b=3
a+b*a/b**2*np.sqrt(a) 

np.float64(2.9428090415820636)

In [ ]:
#broad-casting, increase the every array element by constant
#CN, sending data packets to everyone
marks=np.array([50,60,70])
marks+5

array([55, 65, 75])

In [18]:
A= np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[7,8,9],[4,5,6],[1,2,3]])
A@B.T
# @ performs matrix multiplication
# .T transposes rows and columns

array([[ 50,  32,  14],
       [122,  77,  32],
       [194, 122,  50]])

In [ ]:
#statistical function
arr=np.array([1,2,3,4,5])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr)) #standard deviation is sqrt(var)
print(np.var(arr)) #variance  

3.0
3.0
1.4142135623730951
2.0
